defaults: &defaults
  adapter: sqlite3

development:
  database: openislam_dm_development.sqlite
  <<: *defaults
test:
  database: openislam_dm_test.sqlite
  <<: *defaults
production:
  database: openislam_dm_production.sqlite
  <<: *defaults